esphome:
  name: bewasserungscomputer
  friendly_name: Bewässerungscomputer

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Bewässerungscomputer Hotspot"
    password: "0Aht0PfqaXeu"

captive_portal:

web_server:
  port: 80

api:
  encryption:
    key: "O/46qSOxukvTvuq3AIrwGOnEcdYFXVqz4eE/2J3uEp0="

ota:
  - platform: esphome
    password: "00ce8b7eb7fa40f5dccd9656e6b5b498"

switch:
  - platform: gpio
    pin: GPIO32
    name: "Valve 1"
    id: valve_1
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 3600s
      - switch.turn_off: valve_1

  - platform: gpio
    pin: GPIO33
    name: "Valve 2"
    id: valve_2
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 3600s
      - switch.turn_off: valve_1

  - platform: gpio
    pin: GPIO25
    name: "Valve 3"
    id: valve_3
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 3600s
      - switch.turn_off: valve_1

  - platform: gpio
    pin: GPIO26
    name: "Valve 4"
    id: valve_4
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 3600s
      - switch.turn_off: valve_1

#   - platform: gpio
#     pin: GPIO27
#     name: "Relay 5"
#   - platform: gpio
#     pin: GPIO14
#     name: "Relay 6"
#   - platform: gpio
#     pin: GPIO12
#     name: "Relay 7"
#   - platform: gpio
#     pin: GPIO13
#     name: "Relay 8"


sensor:
  - platform: wifi_signal  # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy  # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

sprinkler:
  - id: garden_sprinkler_ctrlr
    main_switch: "Garten Sprinkler"
    auto_advance_switch: "Garten Sprinkler Auto Advance"
    # reverse_switch: "Garten Sprinkler Reverse"
    # multiplier_number: "Garten Sprinkler Multiplier"
    # repeat_number: "Garten Sprinkler Repeat"
    valve_overlap: 1s
    valves:
      - valve_switch: "Rasen"
        enable_switch: "Aktiviere Rasen"
        run_duration_number: "Rasen Laufzeit"
        valve_switch_id: valve_1
      - valve_switch: "Haus"
        enable_switch: "Aktiviere Haus"
        run_duration_number: "Haus Laufzeit"
        valve_switch_id: valve_2
      - valve_switch: "Hecke"
        enable_switch: "Aktiviere Hecke"
        run_duration_number: "Hecke Laufzeit"
        valve_switch_id: valve_3
      - valve_switch: "Reserve"
        enable_switch: "Aktiviere Reserve"
        run_duration_number: "Reserves Laufzeit"
        valve_switch_id: valve_4

button:
  - platform: restart
    name: "Neu starten"
